name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install Dependencies
      run: |
        npm install

    - name: Build
      run: |
        npm run build

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_IP }}
        username: ${{ secrets.AWS_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: "cd /opt/node/buchim-frontend && git pull origin main && npm install && npm run build && pm2 restart buchim-frontend"
