name: Deploy to EC2

on:
  push:
    branches:
      - main 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_IP }}
        username: ${{ secrets.AWS_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: "cd /opt/node/buchim-frontend && git pull origin main && npm install && pm2 restart all"
